server {
    listen 80;

    root /usr/share/nginx/html;
    resolver 168.63.129.16 ipv6=off valid=10s;

    set $backend https://gateway-backend.bravedune-282fcbdd.germanywestcentral.azurecontainerapps.io;

    location ~* \.(jpg|jpeg|png|gif|svg|css|js|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /api {
        proxy_pass $backend;
        proxy_ssl_server_name on;
        proxy_set_header Host gateway-backend.bravedune-282fcbdd.germanywestcentral.azurecontainerapps.io;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /ai {
        proxy_pass $backend;
        proxy_ssl_server_name on;
        proxy_set_header Host gateway-backend.bravedune-282fcbdd.germanywestcentral.azurecontainerapps.io;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 20M;
    }

    location /trips {
        proxy_pass $backend;
        proxy_ssl_server_name on;
        proxy_set_header Host gateway-backend.bravedune-282fcbdd.germanywestcentral.azurecontainerapps.io;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /blob {
        proxy_pass $backend;
        proxy_ssl_server_name on;
        proxy_set_header Host gateway-backend.bravedune-282fcbdd.germanywestcentral.azurecontainerapps.io;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /health {
        proxy_pass $backend;
        proxy_ssl_server_name on;
        proxy_set_header Host gateway-backend.bravedune-282fcbdd.germanywestcentral.azurecontainerapps.io;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}